--테이블 복사 구문
CREATE TABLE DEPARTMENT2
AS SELECT * FROM DEPARTMENT;

SELECT * FROM DEPARTMENT2;

--새로운 데이터 INSERT 
INSERT INTO DEPARTMENT2 VALUES('T1','개발1팀','L2');
INSERT INTO DEPARTMENT2 VALUES('T2','개발2팀','L2');
INSERT INTO DEPARTMENT2 VALUES('T3','개발3팀','L2');

--INSERT확인
SELECT * FROM DEPARTMENT2;

-->DB에 반영된 것처럼 보이지만
---SQL 수행시 트랜잭션 내용도 포함해서 수행된다.
--(실제로 아직 DB반영 안됐음)

--ROLLBACK 후 확인
ROLLBACK;
SELECT * FROM DEPARTMENT2;


INSERT INTO DEPARTMENT2 VALUES('T1','개발1팀','L2');
INSERT INTO DEPARTMENT2 VALUES('T2','개발2팀','L2');
INSERT INTO DEPARTMENT2 VALUES('T3','개발3팀','L2');

SELECT * FROM DEPARTMENT2;

COMMIT;

ROLLBACK;
SELECT * FROM DEPARTMENT2;


----------------------------------
---SAVEPOINT 확인

INSERT INTO DEPARTMENT2 VALUES('T4','개발4팀','L2');
SAVEPOINT SP1;
INSERT INTO DEPARTMENT2 VALUES('T5','개발5팀','L2');
SAVEPOINT SP2;
INSERT INTO DEPARTMENT2 VALUES('T6','개발6팀','L2');

SELECT * FROM DEPARTMENT2;

-- SP2지점까지 롤백
ROLLBACK TO SP2;
SELECT * FROM DEPARTMENT2; --개발 6팀만 롤백된다.

ROLLBACK;
SELECT * FROM DEPARTMENT2; --개발 4팀 롤백

SELECT * FROM EMPLOYEE
ORDER BY 1 DESC;

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;

SELECT EMP_NAME,DEPT_TITLE  FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);

