
--1. 예전 SQL방식을 허용한다는 뜻
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
--2. 사용자 계정 생성
CREATE USER project_lsy IDENTIFIED BY project1234;

--3.생성한 사용자 계정에 권한 부여
GRANT CONNECT,RESOURCE,CREATE VIEW TO  project_lsy;
--CONNECT  : DB 접속 관련 권한을 묶어둔 ROLE입니다.
--RESOURCE : DB 사용을 위한 기본 객체 생성 권한을 묶어돈 ROLE입니다.
--CREATE VIEW : view  생성할 수 있는 권한

--4.테이블 스페이스 할당
ALTER USER project_lsy DEFAULT
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
--시스템 안에서 무제한으로 TABLESPACE를 활용할 공간을 주겠다.

----------------------------------------------------
--<1> : 손님 테이블 생성
CREATE TABLE MEMBER (
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PW VARCHAR2(30) NOT NULL,
	MEMBER_NM VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK (SECESSION_FL IN ('Y','N'))

);

SELECT * FROM MEMBER;


--주석 달기
COMMENT ON COLUMN "MEMBER".MEMBER_NO IS '회원번호';
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER".MEMBER_NM IS '회원 이름';
COMMENT ON COLUMN "MEMBER".ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN "MEMBER".SECESSION_FL IS '탈퇴여부(Y/N)';

---------------------------------------------
--연습용

--(2)숙소 TABLE
CREATE TABLE HOTEL_EX (
	HOTEL_NO NUMBER PRIMARY KEY,
	LOCATION VARCHAR(5),
	HOTEL_NAME VARCHAR(30),
	PRICE NUMBER,
	ROOM VARCHAR(30),
	RV_FL CHAR(1) DEFAULT 'N' CHECK (RV_FL IN ('Y','N'))
);
--엥 방이름 넣어야 된다;;;;
--주석 달기
COMMEMT ON COLUMN HOTEL_EX.HOTEL_NO IS '호텔번호';
COMMEMT ON COLUMN HOTEL_EX.HOTEL_NO IS '호텔위치';
COMMEMT ON COLUMN HOTEL_EX.HOTEL_NO IS '호텔이름';
COMMEMT ON COLUMN HOTEL_EX.HOTEL_NO IS '가격';
COMMEMT ON COLUMN HOTEL_EX.HOTEL_NO IS '방';
COMMEMT ON COLUMN HOTEL_EX.HOTEL_NO IS '예약여부';

--(3)예약 목록 TABLE
CREATE TABLE RESERVATION_EX (
	RESERVATION_NO NUMBER,
	HOTEL_NO NUMBER REFERENCES HOTEL_EX(HOTEL_NO),
	MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO),
	IN_DATE DATE,
	OUT_DATE DATE,
	PRIMARY KEY(HOTEL_NO,IN_DATE));






































