CREATE TABLE TIMETABLE (
	ALL_MOVIES_NO NUMBER PRIMARY KEY,
	THEATER_NO NUMBER REFERENCES THEATER ON DELETE CASCADE,
	SCREEN_NO NUMBER REFERENCES SCREEN ON DELETE CASCADE,
	MOVIE_NO NUMBER REFERENCES MOVIE ON DELETE SET NULL,
	START_TIME DATE

);

SELECT * FROM TIMETABLE;

COMMIT;

---------------------------------------------------------------

SELECT THEATER_NM,TO_CHAR(START_TIME,'HH24" : "MI')
FROM TIMETABLE 
JOIN THEATER USING (THEATER_NO);

SELECT SCREEN_NAME,TO_CHAR(START_TIME,'HH24" : "MI')
FROM TIMETABLE
JOIN SCREEN USING (SCREEN_NO);

SELECT MOVIE_TITLE,TO_CHAR(START_TIME,'HH24" : "MI')
FROM TIMETABLE
JOIN MOVIE USING (MOVIE_NO)
WHERE MOVIE_TITLE = '화차';


--영화별 상영시간표 
SELECT THEATER_NM, SCREEN_NAME, MOVIE_TITLE,TO_CHAR(START_TIME,'HH24" : "MI')
FROM TIMETABLE T
JOIN THEATER H ON (T.THEATER_NO = H.THEATER_NO)
JOIN SCREEN S ON (T.SCREEN_NO = S.SCREEN_NO)
JOIN MOVIE USING(MOVIE_NO)
WHERE MOVIE_TITLE = '스크림'
AND (TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) < TO_NUMBER(TO_CHAR(START_TIME,'HH24'))
	 OR (TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) = TO_NUMBER(TO_CHAR(START_TIME,'HH24'))
		AND TO_NUMBER(TO_CHAR(SYSDATE,'MI')) = TO_NUMBER(TO_CHAR(START_TIME,'MI'))));


JOIN MOVIE USING (MOVIE_NO);

--극장별 상영시간표
SELECT THEATER_NM, SCREEN_NAME, MOVIE_TITLE,TO_CHAR(START_TIME,'HH24" : "MI')
FROM TIMETABLE T
JOIN THEATER H ON (T.THEATER_NO = H.THEATER_NO)
JOIN SCREEN S ON (T.SCREEN_NO = S.SCREEN_NO)
JOIN MOVIE USING(MOVIE_NO)
WHERE THEATER_NM = '서울점'
AND (TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) < TO_NUMBER(TO_CHAR(START_TIME,'HH24'))
	 OR (TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) = TO_NUMBER(TO_CHAR(START_TIME,'HH24'))
		AND TO_NUMBER(TO_CHAR(SYSDATE,'MI')) = TO_NUMBER(TO_CHAR(START_TIME,'MI'))))
ORDER BY MOVIE_TITLE,START_TIME;
