
--1. 예전 SQL방식을 허용한다는 뜻
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
--2. 사용자 계정 생성
CREATE USER project_lsy IDENTIFIED BY project1234;

--3.생성한 사용자 계정에 권한 부여
GRANT CONNECT,RESOURCE,CREATE VIEW TO  project_lsy;
--CONNECT  : DB 접속 관련 권한을 묶어둔 ROLE입니다.
--RESOURCE : DB 사용을 위한 기본 객체 생성 권한을 묶어돈 ROLE입니다.
--CREATE VIEW : view  생성할 수 있는 권한

--4.테이블 스페이스 할당
ALTER USER project_lsy DEFAULT
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
--시스템 안에서 무제한으로 TABLESPACE를 활용할 공간을 주겠다.

----------------------------------------------------
--<1> : 고객정보 테이블 생성
CREATE TABLE MEMBER (
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PW VARCHAR2(30) NOT NULL,
	MEMBER_NM VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE,
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK (SECESSION_FL IN ('Y','N'))

);

SELECT * FROM MEMBER;


--주석 달기
COMMENT ON COLUMN "MEMBER".MEMBER_NO IS '회원번호';
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER".MEMBER_NM IS '회원 이름';
COMMENT ON COLUMN "MEMBER".ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN "MEMBER".SECESSION_FL IS '탈퇴여부(Y/N)';

---------------------------------------------



--<3> : 영화_영화관번호1 테이블 생성
CREATE TABLE MOVIE (

	THEATER_NO NUMBER REFERENCES ,
	MOVIE_NO NUMBER,
	MOVIE_NM VARCHAR2(30),
	MOVIE_TIME DATE,
	SCREEN_NO NUMBER
	
);

--DROP TABLE MOVIE;

--주석 달기
COMMENT ON COLUMN MOVIE.THEATER_NO IS '영화관번호';
COMMENT ON COLUMN MOVIE.MOVIE_NO IS '영화번호';
COMMENT ON COLUMN MOVIE.MOVIE_NM IS '영화제목';
COMMENT ON COLUMN MOVIE.MOVIE_TIME IS '영화시작시간';
COMMENT ON COLUMN MOVIE.SCREEN_NO IS '상영관번호';


SELECT * FROM MOVIE;

DELETE FROM MOVIE;
DROP SEQUENCE SEQ_MOVIE_NO;
CREATE SEQUENCE SEQ_MOVIE_NO 
START WITH 1
INCREMENT BY 1
NOCYCLE 
NOCACHE;

INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-09-23 07:00:00','YYYY-MM-DD HH24:MI:SS'),1);

INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 09:40:00','YYYY-MM-DD HH24:MI:SS'),1);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 11:20:00','YYYY-MM-DD HH24:MI:SS'),1);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 13:00:00','YYYY-MM-DD HH24:MI:SS'),1);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 15:40:00','YYYY-MM-DD HH24:MI:SS'),1);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 17:30:00','YYYY-MM-DD HH24:MI:SS'),1);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 19:40:00','YYYY-MM-DD HH24:MI:SS'),1);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 21:20:00','YYYY-MM-DD HH24:MI:SS'),1);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 23:40:00','YYYY-MM-DD HH24:MI:SS'),1);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 08:20:00','YYYY-MM-DD HH24:MI:SS'),2);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 10:40:00','YYYY-MM-DD HH24:MI:SS'),2);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 10:40:00','YYYY-MM-DD HH24:MI:SS'),2);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 10:40:00','YYYY-MM-DD HH24:MI:SS'),2);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 10:40:00','YYYY-MM-DD HH24:MI:SS'),2);
INSERT INTO "MOVIE"
VALUES (1,SEQ_MOVIE_NO.NEXTVAL,'공조2-인터내셔날',TO_DATE('2022-9-23 10:40:00','YYYY-MM-DD HH24:MI:SS'),2);
ROLLBACK;

SELECT THEATER_NO,MOVIE_NO,MOVIE_NM,TO_CHAR(MOVIE_TIME,'HH24"시"MI"분"')
FROM MOVIE 
WHERE TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) < TO_NUMBER(TO_CHAR(MOVIE_TIME,'HH24'))
	 OR (TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) = TO_NUMBER(TO_CHAR(MOVIE_TIME,'HH24'))
		AND TO_NUMBER(TO_CHAR(SYSDATE,'MI')) = TO_NUMBER(TO_CHAR(MOVIE_TIME,'MI')));




-------------------------------------------------------------------------------------
--연습해보자
CREATE TABLE "MOVIE1" (

	THEATER_NO NUMBER ,
	MOVIE_NO NUMBER,
	MOVIE_NM VARCHAR2(30),
	MOVIE_TIME DATE,
	SCREEN_NO NUMBER
	
);	

CREATE TABLE "MOVIE2" (

	THEATER_NO NUMBER  ,
	MOVIE_NO NUMBER,
	MOVIE_NM VARCHAR2(30),
	MOVIE_TIME DATE,
	SCREEN_NO NUMBER
	
);

SELECT * FROM MOVIE1;
--INSERT INTO "MOVIE1"
--VALUES (1,1,'화차',TO_DATE('2022-09-24 22:00:00','YYYY-MM-DD HH24:MI:SS'),1);
SELECT THEATER_NO,MOVIE_NO,MOVIE_NM,TO_CHAR(MOVIE_TIME,'YYYY-MM-DD HH24:MI:SS') FROM MOVIE1;
--INSERT INTO "MOVIE2"
--VALUES (2,1,'화차',TO_DATE('2022-09-24 21:45:00','YYYY-MM-DD HH24:MI:SS'),1);
SELECT * FROM MOVIE2;
--INSERT INTO "MOVIE2"
--VALUES (2,1,'화차',TO_DATE('2022-09-24 17:30:00','YYYY-MM-DD HH24:MI:SS'),1);
--INSERT INTO "MOVIE2"
--VALUES (2,1,'화차',TO_DATE('2022-09-24 13:30:00','YYYY-MM-DD HH24:MI:SS'),1);
--INSERT INTO "MOVIE2"
--VALUES (2,1,'화차',TO_DATE('2022-09-24 12:30:00','YYYY-MM-DD HH24:MI:SS'),1);
INSERT INTO "MOVIE2"
VALUES (2,1,'화차',TO_DATE('2022-09-24 23:50:00','YYYY-MM-DD HH24:MI:SS'),1);
SELECT * FROM MOVIE2;

SELECT *FROM MOVIE1 
WHERE MOVIE_NM = '화차'
ORDER BY MOVIE_TIME
UNION 
SELECT *FROM MOVIE2 
WHERE MOVIE_NM = '화차'
ORDER BY MOVIE_TIME;

SELECT *FROM MOVIE2 
WHERE MOVIE_NM = '화차'
ORDER BY MOVIE_TIME;


--영화별 예매 코드

	SELECT THEATER_NO,MOVIE_NM,TO_CHAR(MOVIE_TIME,'HH24" : "MI') FROM MOVIE1 M
	WHERE MOVIE_NM = '화차'
	AND (TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) < TO_NUMBER(TO_CHAR(MOVIE_TIME,'HH24'))
	 OR (TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) = TO_NUMBER(TO_CHAR(MOVIE_TIME,'HH24'))
		AND TO_NUMBER(TO_CHAR(SYSDATE,'MI')) = TO_NUMBER(TO_CHAR(MOVIE_TIME,'MI'))))
	UNION 
	SELECT THEATER_NO,MOVIE_NM,TO_CHAR(MOVIE_TIME,'HH24" : "MI') FROM MOVIE2 N
	WHERE MOVIE_NM = '화차'
	AND(TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) < TO_NUMBER(TO_CHAR(MOVIE_TIME,'HH24'))
	 OR (TO_NUMBER(TO_CHAR(SYSDATE,'HH24')) = TO_NUMBER(TO_CHAR(MOVIE_TIME,'HH24'))
		AND TO_NUMBER(TO_CHAR(SYSDATE,'MI')) = TO_NUMBER(TO_CHAR(MOVIE_TIME,'MI'))))
)
ORDER BY THEATER_NO; 

--극장별 예매 코드

SELECT 
