-- 테스트용 TABLE 생성

CREATE TABLE TB_TEST(
	TEST_NO NUMBER PRIMARY KEY,
	TEST_TITLE VARCHAR2(100) NOT NULL,
	TEST_CONTENT VARCHAR2(500) NOT NULL
);

SELECT * FROM TB_TEST;

UPDATE TB_TEST 
SET TEST_TITLE = '제목변경', TEST_CONTENT = '내용변경'
WHERE  TEST_NO = '10';

ROLLBACK;