SELECT *
FROM TB_DEPARTMENT 

--1번
SELECT STUDENT_NAME 이름 , STUDENT_ADDRESS 주소지
FROM TB_STUDENT 
ORDER BY STUDENT_NAME;

--2번
SELECT STUDENT_NAME ,STUDENT_SSN 
FROM TB_STUDENT 
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;


--3번
SELECT STUDENT_NAME , STUDENT_NO ,STUDENT_ADDRESS 
FROM TB_STUDENT
WHERE  SUBSTR(STUDENT_NO,1,1) = '9' 
AND (SUBSTR(STUDENT_ADDRESS,1,3) = '경기도' OR SUBSTR(STUDENT_ADDRESS,1,3) = '강원도')
ORDER BY STUDENT_NAME;

--4번
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME ='법학과'
ORDER BY PROFESSOR_SSN;

--5번
SELECT STUDENT_NO,TO_CHAR(POINT,9999.99) 학점
FROM TB_GRADE 
WHERE TERM_NO = 200402 AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC ,STUDENT_NO;
 
--6번(O)
--학생번호,학생이름,학과이름
SELECT STUDENT_NO, STUDENT_NAME,DEPARTMENT_NAME 
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

--7번(O)
SELECT CLASS_NAME, DEPARTMENT_NAME 
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

--8번 ?
SELECT C.CLASS_NAME, P.PROFESSOR_NAME 
FROM TB_CLASS C
JOIN TB_PROFESSOR P ON (C.DEPARTMENT_NO = P.DEPARTMENT_NO);

--8번 이렇게 하면 됨.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR  
JOIN TB_CLASS USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);



--9번

--SELECT CLASS_NAME, PROFESSOR_NAME,CATEGORY
--FROM TB_CLASS_PROFESSOR  
--JOIN TB_CLASS USING(CLASS_NO)
--JOIN TB_PROFESSOR  USING(PROFESSOR_NO)
--JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)

--왜 JOIN TB_DEPARTMENT USING (DEPARTMENT_NO) 이거 안되는가?
--ORA-00918: column ambiguously defined 컬럼의 정의가 애매모호하다.
--이런 오류가 날 때에는 중복되는 컬럼명을 구분할 수 있도록 테이블명.컬럼명 또는 별칭.컬럼명으로 구분해주면 된다.

SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR  
JOIN TB_CLASS USING(CLASS_NO)
JOIN TB_PROFESSOR P USING(PROFESSOR_NO)
JOIN TB_DEPARTMENT D USING (P.DEPARTMENT_NO =D.DEPARTMENT_NO)
WHERE CATEGORY ='인문사회';

SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS  
JOIN TB_CLASS_PROFESSOR  USING(CLASS_NO)
JOIN TB_PROFESSOR P USING(PROFESSOR_NO)
JOIN TB_DEPARTMENT D USING (P.DEPARTMENT_NO = D.DEPARTMENT_NO)

--어째서... ㅠ


--9번 답!!!
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR
JOIN TB_CLASS USING(CLASS_NO)
JOIN TB_PROFESSOR P USING(PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON(P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';




--10번?
--음악학과학생들의 전체평점
SELECT S.STUDENT_NO 학번 , S.STUDENT_NAME 학생이름, G.POINT 전체평점
FROM TB_STUDENT S
JOIN TB_GRADE G ON (G.STUDENT_NO = S.STUDENT_NO)
JOIN TB_DEPARTMENT D ON(D.DEPARTMENT_NO = S.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME ='음악학과';


SELECT STUDENT_NO,STUDENT_NAME, ROUND(AVG(POINT),1)
FROM TB_GRADE 
JOIN TB_STUDENT USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME 



--에러난 이유는? 그룹함수... 그룹바이로 묶어줘야 됨.




--11번(O)
--학번 A313047,학과이름,학생이름,지도교수이름


SELECT DEPARTMENT_NAME 학과이름,STUDENT_NAME 학생이름 , PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--12번(O) 


SELECT STUDENT_NAME,TERM_NO
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
JOIN TB_STUDENT USING (STUDENT_NO)
WHERE CLASS_NAME = '인간관계론' 
AND SUBSTR(TERM_NO,1,4)='2007';

--13번(o) 
--(담당과목교슈 배정 안받은 게 뭐임?)
--예체능 계열 과목 중 과목 담당교수를 한 명도 배정받지 못한 과목을 찾아
--그 과목 이름과 학과 이름을 출력하는 SQL 문장을 작성하시오.
--(기존 워크북 PDF에 나타난 조회 결과는 DB 버전이 낮아 현재와 조회 방식이 다름.
--결과 행의 수만 동일하게 조회하자)
--SELECT CATEGORY,DEPARTMENT_NAME,CLASS_NAME
--FROM TB_DEPARTMENT 
--JOIN TB_CLASS USING (DEPARTMENT_NO)
--WHERE DEPARTMENT_NO NOT IN (SELECT DEPARTMENT_NO 
--							FROM TB_PROFESSOR);

--잘못 접근 ㅋ
SELECT DEPARTMENT_NAME,CLASS_NAME
FROM TB_DEPARTMENT
JOIN TB_CLASS USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NO NOT IN (SELECT DISTINCT DEPARTMENT_NO 
							FROM TB_PROFESSOR WHERE DEPARTMENT_NO IS NOT NULL)
AND CATEGORY = '예체능';

--13번 답
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
WHERE PROFESSOR_NO IS NULL AND CATEGORY = '예체능';

--풀이
SELECT COUNT(*) FROM TB_CLASS --CLASS_NO 882과목이 조회됨.(총 과목)

SELECT COUNT(*) FROM TB_CLASS_PROFESSOR --CLASS_NO 776과목이 조회됨.(교수가 있는 과목)

--아직 교수가 배정이 안 된 과목은 PROFESSOR_NO가 NULL이라고 써진 거임
----------------------------------------------------------------
--서브쿼리로 풀 경우 13번 답
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
AND CLASS_NO NOT IN (SELECT CLASS_NO FROM TB_CLASS_PROFESSOR )

--------------------------------------------------------


--14번
--학과: 서반아이어/지도교수

--1. 왜 널값없어
--2. 왜 JOIN을 반대로 하면 안되는뎅 왜!!!

SELECT STUDENT_NAME, COACH_PROFESSOR_NO , PROFESSOR_NAME 
FROM TB_STUDENT S
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT D USING (S.DEPARTMENT_NO)


SELECT DEPARTMENT_NAME,STUDENT_NAME,PROFESSOR_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME  = '서반아어학과'





--15번(o)
--휴학생이 아닌 학생 & 평점 4.0
--학번,이름,학과이름,평점

SELECT STUDENT_NAME,ABSENCE_YN ,AVG(POINT)
FROM TB_STUDENT 
JOIN TB_GRADE USING(STUDENT_NO)
GROUP BY STUDENT_NO,STUDENT_NAME
HAVING AVG(POINT)>= 4.0;


SELECT STUDENT_NAME,DEPARTMENT_NAME,STUDENT_NO,AVG(POINT)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME,DEPARTMENT_NAME
HAVING AVG(POINT)>=4.0;

--18번

SELECT STUDENT_NO, STUDENT_NAME ,AVG(POINT) 평점
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO,STUDENT_NAME
ORDER BY 평점 DESC;

--이걸 서브쿼리로 잡고

SELECT STUDENT_NO, STUDENT_NAME
FROM (SELECT STUDENT_NO, STUDENT_NAME ,AVG(POINT) 평점
	FROM TB_GRADE
	JOIN TB_STUDENT USING (STUDENT_NO)
	JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
	WHERE DEPARTMENT_NAME = '국어국문학과'
	GROUP BY STUDENT_NO,STUDENT_NAME
	ORDER BY 평점 DESC)
WHERE ROWNUM=1;
--이렇게!

--다른 답(JOIN을 한번 덜쓰니까 속도 더 빨라진다.)
SELECT STUDENT_NO, STUDENT_NAME
FROM (SELECT STUDENT_NO, STUDENT_NAME ,AVG(POINT) 평점
	FROM TB_GRADE
	JOIN TB_STUDENT USING (STUDENT_NO)
	WHERE DEPARTMENT_NO =(SELECT DEPARTMENT_NO 
						FROM TB_DEPARTMENT
						WHERE DEPARTMENT_NAME = '국어국문학과')
	GROUP BY STUDENT_NO,STUDENT_NAME
	ORDER BY 평점 DESC)
WHERE ROWNUM=1;

--단일행(단일열) 서브쿼리
SELECT DEPARTMENT_NO 
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '국어국문학과'

--------------------------------------------
--19번
SELECT CATEGORY 
FROM TB_DEPARTMENT

--(1)환경조경학과가 무슨 학과임? -- 자연과학
SELECT *
FROM TB_DEPARTMENT 
WHERE DEPARTMENT_NAME = '환경조경학과'

--(2) 전공과목인 경우는
SELECT *
FROM TB_CLASS
WHERE CLASS_TYPE = '전공선택'

--(3) 19번 답
SELECT DEPARTMENT_NAME "계열 학과명",ROUND(AVG(POINT),1) 전공평점
FROM TB_DEPARTMENT
JOIN TB_CLASS USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(CLASS_NO)
WHERE CATEGORY =(SELECT CATEGORY 
				FROM TB_DEPARTMENT
				WHERE DEPARTMENT_NAME = '환경조경학과')
AND CLASS_TYPE LIKE '전공%'
GROUP BY DEPARTMENT_NAME
ORDER BY 1;



